README.md
- Add the project page and LlamaIndex link to README.
=> Feature(LLMLingua): update the news

llmlingua/prompt_compressor.py
=> Fixed (LLMLingua): Resolved the issue where the context was coming up as empty

llmlingua/prompt_compressor.py
- Fix the "prefix dimension mismatch" issue.
=> Fixed(LLMLingua): fix the prefix dimension mismatch.

DOCUMENT.md
Recommandation -> Recommendation
=> Fix(LLMLingua): fix typo in DOCUMENT.md

README.md
- Add slide for AI Time Jan, 24.
=> Feature(LLMLingua): add slide of AI Time.

README.md
- Add the demo reference link, [alt-gpt](https://github.com/feedox/alt-gpt). Special thanks to @Livshitz for their valuable contribution.
=> Feature(LLMLingua): add alt-gpt reference

llmlingua/prompt_compressor.py
- fixed a potential ZeroDivisionError caused by the actual compression ratio in #53
=> Fix (LLMLingua): Resolved a potential ZeroDivisionError caused by the actual compression ratio.

README.md, examples/RAGLlamaIndex.ipynb
fix wrong llamaindex pipeline link
=> Fix (LLMLingua): fix the link of llama_index

DOCUMENT.md, README.md
- support `phi-2` model in #51.
=> Feature(LLMLingua): support phi-2

llmlingua/prompt_compressor.py
This pull request introduces detailed docstrings for the PromptCompressor class and its primary method compress_prompt in our codebase. These additions are intended to enhance the understandability and maintainability of our prompt compression feature. #51
=> Feature (LLMLingua): Add Docstring for PromptCompressor Class

llmlingua/prompt_compressor.py
- fix the out of range due to the very short sentence.
=> Hotfix (LLMLingua): fix the out of range

Transparency_FAQ.md
=> Feature(LLMLingua): update the FAQ

llmlingua/prompt_compressor.py
Change parameter from ratio to rate.
Compression rate = compressed size / raw size (lower is better)
=> change input parameter from ratio to rate

DOCUMENT.md, README.md, Transparency_FAQ.md, examples/RAGLlamaIndex.ipynb, tests/test_llmlingua.py, tests/test_longllmlingua.py
- add LangChain example, thanks to @thehapyone's contribution.
=> Feature(LLMLingua): add LangChain example

README.md
- update conference of LongLLMLingua.
=> Feature(LongLLMLingua): update conference

.github/workflows/release.yml
=> Fix(LLMLingua): fix the release workflows

.github/workflows/release.yml
=> Fix(LLMLingua): fix the release workflow

llmlingua/prompt_compressor.py, llmlingua/version.py
=> Release(LLMLingua): release v0.2.0

README.md, llmlingua/prompt_compressor.py
=> Feature(LLMLingua-2): fix the title

README.md
=> Feature(LLMLingua): add MInference News

.github/workflows/unittest.yml, README.md, examples/LLMLingua2.ipynb, examples/RAG.ipynb, examples/RAGLlamaIndex.ipynb
- Update the ACL links;
to it if that's the case.
@iofu728
=> Feature(LLMLingua): update ACL links

experiments/llmlingua2/model_training/train.sh, experiments/llmlingua2/model_training/train_roberta.py
Saves model in huggingface style, so that a user can directly load the trained model.
Fixes # (issue)
to it if that's the case.
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
<!-- Your PR will be replied to more quickly if you can figure out the right person to tag with @
If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.
Please tag fewer than 3 people.
LLMLingua/LongLLMLingua:
- general: @iofu728, @QianhuiWu, @XufangLuo, and @mydmdm
- new feature: @SiyunZhao
Documentation: @SiyunZhao
=> [LLMLingua2] Save model in huggingface style

llmlingua/utils.py
To support other small bert-like models (e.g., tinyBERT, mobileBERT) for LLMLingua2
to it if that's the case.
@iofu728, @QianhuiWu
=> support fine-tuned tinybert and mobilebert
